### ISSUE TITLE
Scroll-Arrow not perfectly centered on mobile devices

### ISSUE THREAD

**Issue by joelklingler** [joelklingler/portfolio#5]
The scroll-info-arrow is not perfectly centered on mobile devices:
![capture](https://cloud.githubusercontent.com/assets/9310366/22946898/3d34c35a-f2f9-11e6-8c4e-4aaaf398a130.PNG)

**Comment by lucahuber** [comment]
Fixed

**Comment by joelklingler** [comment]
Font awesome update broke it.
